spring.application.name=echobeacon
spring.security.user.name=admin
spring.security.user.password=admin

spring.security.oauth2.client.registration.github.client-id=Ov23liqcpM03g030txIr
spring.security.oauth2.client.registration.github.client-secret=3f5991f7161b25b1f98efba51cd103a6b3e7acca
